### PR TITLE
RM-103673 Release json_schema 3.0.1

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [Raise w_transport max to <5.0.0](https://github.com/Workiva/json_schema/pull/82)

Requested by: @robbecker-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/3.0.0...Workiva:release_json_schema_3.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/3.0.0...3.0.1

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5466858621239296/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?pull_number=83&repo_name=Workiva%2Fjson_schema)

### CODE REVIEW

**Review by evanweible-wf — APPROVED** [review]

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (3.0.0) as the diff base.</strong></em></p> No changes to the public API found for commit 424e2d026298fa8294e5744fbf7afa1d7c0ae7fe

Showing results for 424e2d026298fa8294e5744fbf7afa1d7c0ae7fe
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/424e2d026298fa8294e5744fbf7afa1d7c0ae7fe).

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
