### PR TITLE
af_new_drydock_image

### PR DESCRIPTION
**Pull request by dustinlessard-wf**
## Purpose

The following pull request has been created by App Frameworks to help move consumers to the latest Smithy image. This was done because of an issue with Dartium and Content-Shell that would fail your CIs. Please seethis [Wiki Question](https://wiki.atl.workiva.net/cq/viewquestion.action?id=96308901&answerId=96308907)for additional context.

## Changes

The following changes have been made:
* All instances of the production Smithy image have been updated to `drydock-prod.workiva.net/workiva/smithy-runner-generator:355624`.

## Questions

If you have any questions, please reach out to us in the Support:H5 / Dart Hipchat room

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit d2c0aca6d43ed72821a298317e84df1a7fff1344

Showing results for d2c0aca6d43ed72821a298317e84df1a7fff1344
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by semver-audit-dart 1.4.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/d2c0aca6d43ed72821a298317e84df1a7fff1344).

**Comment by michaelcarter-wf** [comment]
This repo builds on Travis, do we still need this @dustinlessard-wf?

**Comment by robbecker-wf** [comment]
@michaelcarter-wf Looking at the smithy.yaml and Dockerfile ... this repo does not run any tests with either content-shell or dartium. So, we could just close this PR or just merge it in. If someone in the future decides to run tests in Workiva build with the old image, they will get the expired Dartium problem and their tests will hang.

**Comment by robbecker-wf** [comment]
+1

**Comment by robbecker-wf** [comment]
+10 CI passes (moved to Workiva build)

**Comment by michaelcarter-wf** [comment]
+10 / +1

**Pull request merged**
