### PR TITLE
EPL-9779: 2.0.0 WIP

### PR DESCRIPTION
**Pull request by michaelcarter-wf**
## Ultimate problem:
- Need to release breaking changes together in a 2.0 release.

## How it was fixed:
- Merge 2.0 WIP Branch

## Testing suggestions:
- CI

## Note:
- all included commits were reviewed in individual PRs.

## Potential areas of regression:
- NA, checked in constituent PRs.

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 Recommendation: **:bangbang: Major version bump**


```diff
@@ line 133: package:json_schema/json_schema.dart @@
-  set uriValidator(null);
// Removing a top-level variable is a major change.
```

```diff
@@ line 136: package:json_schema/json_schema.dart @@
-  set emailValidator(null);
// Removing a top-level variable is a major change.
```

```diff
@@ line 139: package:json_schema/json_schema.dart @@
-  bool logFormatExceptions = false;
// Removing a top-level variable is a major change.
```

```diff
@@ line 324: package:json_schema/schema_dot.dart @@
-  String createDot(Schema schema);
+  String createDot(JsonSchema schema);
// `type` of `schema` has changed.
// Changing a parameter signature is a major change.
```

```diff
@@ line 41: package:json_schema/src/json_schema/schema.dart @@
-  class Schema {}
// Removing a class is a major change.

-     Schema get notSchema;
//    Removing a field is a major change.

-     bool propertyRequired(String property);
//    Removing a method is a major change.

-     List<Schema> get itemsList;
//    Removing a field is a major change.

-     Map<String, Schema> get schemaDependencies;
//    Removing a field is a major change.

-     Map<RegExp, Schema> get patternProperties;
//    Removing a field is a major change.

-     int get minProperties;
//    Removing a field is a major change.

-     Map<dynamic, dynamic> get schemaMap;
//    Removing a field is a major change.

-     String get ref;
//    Removing a field is a major change.

-     String get description;
//    Removing a field is a major change.

-     Schema get root;
//    Removing a field is a major change.

-     int get maxLength;
//    Removing a field is a major change.

-     bool get uniqueItems;
//    Removing a field is a major change.

-     bool get exclusiveMinimum;
//    Removing a field is a major change.

-     Map<String, Schema> get refMap;
//    Removing a field is a major change.

-     num get maximum;
//    Removing a field is a major change.

-     dynamic get defaultValue;
//    Removing a field is a major change.

-     num get multipleOf;
//    Removing a field is a major change.

-     List<Schema> get anyOf;
//    Removing a field is a major change.

-     int get minLength;
//    Removing a field is a major change.

-     RegExp get pattern;
//    Removing a field is a major change.

-     List<SchemaType> get schemaTypeList;
//    Removing a field is a major change.

-     Map<String, Schema> get properties;
//    Removing a field is a major change.

-     Schema get items;
//    Removing a field is a major change.

-     Schema resolvePath(String path);
//    Removing a method is a major change.

-     List<Schema> get allOf;
//    Removing a field is a major change.

-     String get title;
//    Removing a field is a major change.

-     Future<Schema> createSchemaFromUrl(String schemaUrl);
//    Removing a method is a major change.

-     int get minItems;
//    Removing a field is a major change.

-     Set<dynamic> get paths;
//    Removing a field is a major change.

-     Map<String, List<String>> get propertyDependencies;
//    Removing a field is a major change.

-     bool get additionalProperties;
//    Removing a field is a major change.

-     Map<String, Schema> get definitions;
//    Removing a field is a major change.

-     dynamic get additionalItems;
//    Removing a field is a major change.

-     String toString();
//    Removing a method is a major change.

-     bool validate(dynamic instance);
//    Removing a method is a major change.

-     num get minimum;
//    Removing a field is a major change.

-     String endPath(String path);
//    Removing a method is a major change.

-     String get path;
//    Removing a field is a major change.

-     int get maxItems;
//    Removing a field is a major change.

-     List<Schema> get oneOf;
//    Removing a field is a major change.

-     List<String> get requiredProperties;
//    Removing a field is a major change.

-     int get maxProperties;
//    Removing a field is a major change.

-     Schema get additionalPropertiesSchema;
//    Removing a field is a major change.

-     List<dynamic> get enumValues;
//    Removing a field is a major change.

-     bool get exclusiveMaximum;
//    Removing a field is a major change.

-     Future<Schema> createSchema(Map data);
//    Removing a method is a major change.

-     Uri get id;
//    Removing a field is a major change.

      From dart:core/object.dart
-     Type get runtimeType;
//    Removing a field is a major change.
-     int get hashCode;
//    Removing a field is a major change.
-     bool ==(other);
//    Removing a method is a major change.
-     dynamic noSuchMethod(Invocation invocation);
//    Removing a method is a major change.

```
<details>
<summary>Click to see 10 more API Changes</summary><p>

---
```diff
@@ line 41: package:json_schema/src/json_schema/validator.dart @@
class Validator {}
-     Validator(this._rootSchema);
+     Validator(this._rootSchema);
//    `type` of `_rootSchema` has changed.
//    Changing a parameter signature is a major change.

```

```diff
@@ line 47: package:json_schema/schema_dot.dart @@
class SchemaNode {}
-     SchemaNode(Schema this.schema, [this.links]);
+     SchemaNode(this.schema, [this.links]);
//    `type` of `schema` has changed.
//    Changing a parameter signature is a major change.

-     Schema schema;
+     JsonSchema schema;
//    `type` of `schema` has changed.
//    Changing a class field is a major change.

-     dynamic schemaType(Schema schema);
+     dynamic schemaType(JsonSchema schema);
//    `type` of `schema` has changed.
//    Changing a parameter signature is a major change.

-     bool schemaShown(Schema schema);
+     bool schemaShown(JsonSchema schema);
//    `type` of `schema` has changed.
//    Changing a parameter signature is a major change.

-     dynamic makeSchemaLink(String port, Schema src, Schema target);
+     dynamic makeSchemaLink(String port, JsonSchema src, JsonSchema target);
//    `type` of `src` has changed.
//    Changing a parameter signature is a major change.

-     dynamic makeSchemaPort(String port, Schema schema);
+     dynamic makeSchemaPort(String port, JsonSchema schema);
//    `type` of `schema` has changed.
//    Changing a parameter signature is a major change.

```

```diff
@@ line 48: package:json_schema/browser.dart @@
+  void configureJsonSchemaForBrowser();
// Adding a top-level function is a minor change.
```

```diff
+ json_schema/browser.dart

// Adding an entry point is a minor change.
```

```diff
@@ line 46: package:json_schema/src/json_schema/browser/platform_functions.dart @@
+  Future<JsonSchema> createSchemaFromUrlBrowser(String schemaUrl, {String schemaVersion});
// Adding a top-level function is a minor change.
```

```diff
+ json_schema/vm.dart

// Adding an entry point is a minor change.
```

```diff
@@ line 46: package:json_schema/src/json_schema/vm/platform_functions.dart @@
+  Future<JsonSchema> createSchemaFromUrlVm(String schemaUrl, {String schemaVersion});
// Adding a top-level function is a minor change.
```

```diff
@@ line 46: package:json_schema/vm.dart @@
+  void configureJsonSchemaForVm();
// Adding a top-level function is a minor change.
```

```diff
@@ line 65: package:json_schema/src/json_schema/json_schema.dart @@
+  class JsonSchema {}
// Adding a class is a minor change.

+     RegExp get pattern;
//    Adding a field is a minor change.

+     List<JsonSchema> get itemsList;
//    Adding a field is a minor change.

+     Map<String, List<String>> get propertyDependencies;
//    Adding a field is a minor change.

+     List<dynamic> get enumValues;
//    Adding a field is a minor change.

+     String get schemaVersion;
//    Adding a field is a minor change.

+     bool validate(dynamic instance);
//    Adding a method is a minor change.

+     bool get schemaBool;
//    Adding a field is a minor change.

+     Future<JsonSchema> createSchemaFromUrl(String schemaUrl, {String schemaVersion});
//    Adding a method is a minor change.

+     int get maxProperties;
//    Adding a field is a minor change.

+     Map<RegExp, JsonSchema> get patternProperties;
//    Adding a field is a minor change.

+     Map<String, JsonSchema> get properties;
//    Adding a field is a minor change.

+     int get maxLength;
//    Adding a field is a minor change.

+     Uri get id;
//    Adding a field is a minor change.

+     List<JsonSchema> get allOf;
//    Adding a field is a minor change.

+     JsonSchema createSchema(dynamic data, {String schemaVersion, Uri fetchedFromUri});
//    Adding a method is a minor change.

+     num get minimum;
//    Adding a field is a minor change.

+     num get maximum;
//    Adding a field is a minor change.

+     Map<String, JsonSchema> get schemaDependencies;
//    Adding a field is a minor change.

+     String endPath(String path);
//    Adding a method is a minor change.

+     JsonSchema resolvePath(String path);
//    Adding a method is a minor change.

+     String get format;
//    Adding a field is a minor change.

+     JsonSchema get notSchema;
//    Adding a field is a minor change.

+     bool propertyRequired(String property);
//    Adding a method is a minor change.

+     int get minLength;
//    Adding a field is a minor change.

+     JsonSchema get root;
//    Adding a field is a minor change.

+     bool get hasConst;
//    Adding a field is a minor change.

+     bool get uniqueItems;
//    Adding a field is a minor change.

+     int get minProperties;
//    Adding a field is a minor change.

+     Map<String, JsonSchema> get refMap;
//    Adding a field is a minor change.

+     List<JsonSchema> get anyOf;
//    Adding a field is a minor change.

+     JsonSchema get propertyNamesSchema;
//    Adding a field is a minor change.

+     bool get additionalProperties;
//    Adding a field is a minor change.

+     Set<dynamic> get paths;
//    Adding a field is a minor change.

+     List<JsonSchema> get oneOf;
//    Adding a field is a minor change.

+     bool get hasExclusiveMaximum;
//    Adding a field is a minor change.

+     List<String> get requiredProperties;
//    Adding a field is a minor change.

+     dynamic get defaultValue;
//    Adding a field is a minor change.

+     String get path;
//    Adding a field is a minor change.

+     num get multipleOf;
//    Adding a field is a minor change.

+     Map<String, JsonSchema> get definitions;
//    Adding a field is a minor change.

+     num get exclusiveMinimum;
//    Adding a field is a minor change.

+     JsonSchema get contains;
//    Adding a field is a minor change.

+     num get exclusiveMaximum;
//    Adding a field is a minor change.

+     JsonSchema get additionalPropertiesSchema;
//    Adding a field is a minor change.

+     int get minItems;
//    Adding a field is a minor change.

+     dynamic get additionalItems;
//    Adding a field is a minor change.

+     Map<dynamic, dynamic> get schemaMap;
//    Adding a field is a minor change.

+     String toString();
//    Adding a method is a minor change.

+     String get description;
//    Adding a field is a minor change.

+     JsonSchema get items;
//    Adding a field is a minor change.

+     List<SchemaType> get schemaTypeList;
//    Adding a field is a minor change.

+     String get title;
//    Adding a field is a minor change.

+     int get maxItems;
//    Adding a field is a minor change.

+     Uri get ref;
//    Adding a field is a minor change.

+     Future<JsonSchema> createSchemaAsync(dynamic data, {String schemaVersion, Uri fetchedFromUri});
//    Adding a method is a minor change.

+     bool get hasExclusiveMinimum;
//    Adding a field is a minor change.

+     dynamic get constValue;
//    Adding a field is a minor change.

```

```diff
@@ line 75: package:json_schema/src/json_schema/constants.dart @@
+  class JsonSchemaVersions {}
// Adding a class is a minor change.

+     static String get draft4;
//    Adding a field is a minor change.

+     static String get draft6;
//    Adding a field is a minor change.

+     static List<String> allVersions = const [draft4, draft6];
//    Adding a field is a minor change.

+     JsonSchemaVersions();
//    Adding a constructor is a minor change.

```
---

</p></details>

Showing results for 16823808836d8b41a104b8d47996b8955adebd68
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by semver-audit-dart 1.4.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/16823808836d8b41a104b8d47996b8955adebd68).

**Comment by shawnrusaw-wf** [comment]
+1 code review

**Comment by michaelcarter-wf** [comment]
+10 

- [x] CI Passes
- [x] All constituent PRs previously reviewed.

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-pp

**Comment by michaelcarter-wf** [comment]
semver +1

**Comment by shawnrusaw-wf** [comment]
semver +1

**Pull request merged**
