### PR TITLE
refactor: update to sound null safety

### LINKED ISSUE #80: Update to sound null-safety
The current version of the package is not null-safe. 

Please update. https://dart.dev/null-safety/migration-guide

> __FYI:__ @michaelcarter-wf

### PR DESCRIPTION
**Pull request by JKRhb**
## Ultimate problem:

The library does not support sound null safety, yet. This PR fixes the issue and resolves #80.

## How it was fixed:

After running `dart migrate`, I manually completed the null safety migration. ~~There are still a lot of failing tests, so the process is not yet finished. I hope to complete it over the next days.~~

## Testing suggestions:

All existing tests should pass, only minimal changes have been applied to them.

## Potential areas of regression:

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by JKRhb** [comment]
@michaelcarter-wf This PR should now be ready for review :) Let me know if anything should be changed.

**Comment by JKRhb** [comment]
@michaelcarter-wf Could you maybe have a look on this PR?

**Comment by michaelcarter-wf** [comment]
So sorry for the lag here @JKRhb! I'm taking a look

**Comment by JKRhb** [comment]
> So sorry for the lag here @JKRhb! I'm taking a look

Awesome, thank you :) Let me know if there is anything that should be changed.

**Comment by JKRhb** [comment]
@michaelcarter-wf Sorry to bother again, but did you find the time yet to have a look? Maybe you could let the CI tests run for this PR? That could account for the fact that the PR is a bit too large to be easily reviewed :/

**Comment by JKRhb** [comment]
Ahem, sorry to bother you again, but: ping @michaelcarter-wf?

**Comment by JKRhb** [comment]
Hmm, do you think this PR could still be useful, or are you planning to implement sound null-safety yourself/from the ground up? In the latter case, we could consider closing this PR. Just let me know once you release a new version so that I could mark the `json_schema3` fork as discontinued.

If the PR could still be used, I would perform a rebase to incorporate the latest changes.

**Review by kyleferguson-wk — APPROVED** [review]

**Comment by kyleferguson-wk** [comment]
This looks like it has a conflict with master, but just a small one in pubspec. Resolved that and ran tests locally, every thing is passing so QA +1 on this, but we'll need to get that conflict resolved first. I can push that up 👍

**Comment by kyleferguson-wk** [comment]
Oh looks like you just resolved that conflict, awesome sauce!

**Comment by JKRhb** [comment]
> Oh looks like you just resolved that conflict, awesome sauce!

Yeah, I got the notification and started resolving it right away 😅 Hope that everything still works :)

**Comment by kyleferguson-wk** [comment]
I'm terribly sorry for our absence on this, we just haven't been able to allocate much time or resources to this repo for a bit, but we really appreciate the work on this PR, stellar work! 🎉

**Comment by JKRhb** [comment]
> I'm terribly sorry for our absence on this, we just haven't been able to allocate much time or resources to this repo for a bit, but we really appreciate the work on this PR, stellar work! 🎉

No problem at all, thank you for providing this package :)

**Comment by kyleferguson-wk** [comment]
+10 re-up

We usually like to have at least 2 eyes on PRs so I'll bug Carter to get eyes on this too since he is a bit more familiar with this repo than I; I forget if he is in today but we'll definitely work to get this through ASAP 👍

**Comment by kyleferguson-wk** [comment]
CI failed but looks just to be due to formatting should be a quick fix `make format` and then commit formatted changes. Should expect to just see `lib/src/json_schema/json_schema.dart` updated from the format

**Comment by kyleferguson-wk** [comment]
+10 re-re-up 🎉 🎉 
- [x] Ran tests locally
- [x] CI passing

**Review by michaelcarter-wf — APPROVED** [review]
+1

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@JKRhb Thank you so much for your contributions here and apologies for the delay. We're going to cut this as 5.0.0-rc1, test internally, then we'll cut a 5.0.1 once we confirm consumption is good.

**Comment by teresarevious-wf** [comment]
RM +1 verified dependencies on the release PR  https://github.com/Workiva/json_schema/pull/152

**Comment by JKRhb** [comment]
> @JKRhb Thank you so much for your contributions here and apologies for the delay. We're going to cut this as 5.0.0-rc1, test internally, then we'll cut a 5.0.1 once we confirm consumption is good.

Thank you for merging! :) And you're welcome!

**Pull request merged**
