### PR TITLE
EPL-6673 Release json_schema 1.0.9

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pulls Included in Release:
* [EPL-6666 feat(package): add semver_audit checks](https://github.com/Workiva/json_schema/pull/5)
* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/json_schema/pull/10)
* [Update .gitignore to new `dart_tool` pub cache](https://github.com/Workiva/json_schema/pull/16)
* [af_new_drydock_image](https://github.com/Workiva/json_schema/pull/18)
* [fix a Completer's type](https://github.com/Workiva/json_schema/pull/22)

Requested by: @michaelcarter-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/1.0.8...Workiva:release_json_schema_1_0_9
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/1.0.8...1.0.9

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5466858621239296/logs/)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (1.0.8) as the diff base.</strong></em></p> No audit found for base commit 98208e8b33f8df7470f3415f694f46d3f0173266

Please check that the commit listed above has run semver_audit.

This issue is normally fixed by rerunning CI for the base commit and
then the current commit. You may also fix this manually:

Check out the base commit locally. For releases, this is the commit for the
previous release called out above. Otherwise it is this Pull Requests's base
commit. Run:

`pub run semver_audit report --repo Workiva/<repo> --head-commit <full_commit_number>`

Now either rerun the Pull Request's CI or run:

`pub run semver_audit report --repo Workiva/<repo> --base-commit <base_commit_number> --head-commit <head_commit_number> --pull <pull_number>`

If this does not resolve the issue, please tag `@Workiva/app-frameworks` for support.


Showing results for ee5e7e4a29e5f07affe45b0a35ef8f7cddd3321d
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by semver-audit-dart 1.4.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/ee5e7e4a29e5f07affe45b0a35ef8f7cddd3321d).

**Comment by michaelcarter-wf** [comment]
+1 / +10

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
