### PR TITLE
PROC-709 fix(test): fix test cases involving formats

### PR DESCRIPTION
**Pull request by michaelcarter-wf**
## Ultimate problem:
- We were not ignoring non-strings in formatted fields as per spec.

## How it was fixed:
- Ignore them

## Potential areas of regression:

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit a365bd8cb631931f179332e7f49f434a9a481ed0

Showing results for a365bd8cb631931f179332e7f49f434a9a481ed0
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.1
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/a365bd8cb631931f179332e7f49f434a9a481ed0).

**Review by jordanross-wf — APPROVED** [review]

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
