### PR TITLE
fix(package): don't depend on dart_dev

### PR DESCRIPTION
**Pull request by michaelcarter-wf**
## Ultimate problem:
- dart_dev isn't null safe yet, and we use it very minimally

## How it was fixed:
- remove the dependency in favor of a short Makefile
- update readme to make it more clear how to get started developing

## Potential areas of regression:

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by michaelcarter-wf** [comment]
+10 

- [x] CI Passes

**Review by jordanross-wf — APPROVED** [review]
+1
@Workiva/release-management-pp

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
