### PR TITLE
chore(package): switch to a json pointer lib that has null safety

### PR DESCRIPTION
**Pull request by michaelcarter-wf**
## Ultimate problem:
- json_pointer library is unmaintained.

## How it was fixed:
- switch to rfc_6901

## Potential areas of regression:

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by jordanross-wf — APPROVED** [review]
+1

**Comment by michaelcarter-wf** [comment]
+10 

- [x] CI Passes

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
