### PR TITLE
Make compatible with Dart 1 and Dart 2 constant names

### PR DESCRIPTION
**Pull request by leafpetersen**
## Ultimate problem:

SCREAMING CAPS constants have been removed as of Dart 2.0.0-dev.69.2 .  This package will no longer work with any dev or stable releases going forward without fixes.  

## How it was fixed:

This PR uses the dart2_constant package to fix this in a way that is still backwards compatible with Dart 1.  References to constants that have changed their names in Dart 2 are re-directed through the dart_constant package which uses pub version solving to back this with the appropriate SDK constants.

## Potential areas of regression:

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by leafpetersen** [comment]
@michaelcarter-wf I see you've been active in this repo recently, any chance you can help out getting this landed?  This package is used by the Flutter repo, so it's important to get a Dart 2 clean version of this published.   cc @kevmoo

**Comment by michaelcarter-wf** [comment]
@leafpetersen thanks for the submission, definitely don't want to hold up any dart 2.0 updates! :)

While the final 2.0 release is baking, @robbecker-wf and I will cut a 1.0.10 branched off of 1.0.9 tag as well.

**Comment by michaelcarter-wf** [comment]
+10 

- [x] CI passes

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-pp

**Comment by leafpetersen** [comment]
Thanks.  Just added a patch bumping the SDK constraint.

**Comment by michaelcarter-wf** [comment]
sorry, wasn't very specific, can we bump the minimum to 1.24 as well? That's what all the dev for 2.0 was done on

**Comment by michaelcarter-wf** [comment]
FYI @leafpetersen we've also cut 1.0.10, which has similar changes, but branched off 1.0.9 tag

**Comment by leafpetersen** [comment]
Done, thanks.

**Comment by michaelcarter-wf** [comment]
+10

- [x] CI Passes

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
