### PR TITLE
WAP-2350 Release json_schema 2.1.0

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* [WAP-2264: Convenience getters around property names and required properties](https://github.com/Workiva/json_schema/pull/41)

Requested by: @michael.carter

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.0.1...Workiva:release_json_schema_2.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.0.1...2.1.0

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5466858621239296/logs/)

### CODE REVIEW

**Comment by michaelcarter-wf** [comment]
+1

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (2.0.1) as the diff base.</strong></em></p> Recommendation: **:warning: Minor version bump**


```diff
@@ line 65: package:json_schema/src/json_schema/json_schema.dart @@
class JsonSchema {}
+     String get propertyName;
//    Adding a field is a minor change.

+     bool get requiredOnParent;
//    Adding a field is a minor change.

+     bool ==(dynamic other);
//    Adding a method is a minor change.

+     JsonSchema get parent;
//    Adding a field is a minor change.

```

Showing results for e1d33849da15f4ed5bca9e1dc2bf432f63eb1daf
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.0.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/e1d33849da15f4ed5bca9e1dc2bf432f63eb1daf).

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
