### PR TITLE
PROC-877 Release json_schema 3.0.0

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* [CPLAT-7426 Run Dart 2 unit tests with dart2js](https://github.com/Workiva/json_schema/pull/60)
* [CPRO-358 fix(ref-resolution): Logic changes around remote ref resolution](https://github.com/Workiva/json_schema/pull/67)
* [WAP-9699: dart_dev upgrade](https://github.com/Workiva/json_schema/pull/69)
* [CPRO-350 Dart1 removal phase 2 and 3](https://github.com/Workiva/json_schema/pull/70)
* [CPRO-359: chore(package): update spec tests](https://github.com/Workiva/json_schema/pull/72)
* [PROC-709 fix(test): fix test cases involving formats](https://github.com/Workiva/json_schema/pull/73)
* [PROC-727 Ref Storage on Schemas and Path Resolution Changes](https://github.com/Workiva/json_schema/pull/74)
* [PROC-728: Fix Encoding and UTF-16 Spec Tests](https://github.com/Workiva/json_schema/pull/75)
* [PROC-735 JSON Schema Draft 7 Support](https://github.com/Workiva/json_schema/pull/76)
* [PROC-876: V3 README Update](https://github.com/Workiva/json_schema/pull/78)

Requested by: @michaelcarter-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.2.1...Workiva:release_json_schema_3.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.2.1...3.0.0

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5466858621239296/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?pull_number=79&repo_name=Workiva%2Fjson_schema)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (2.2.1) as the diff base.</strong></em></p> Recommendation: **:bangbang: Major version bump (fyi @Workiva/semver-audit-group )**


```diff
@@ line 45: package:json_schema/src/json_schema/typedefs.dart @@
-  typedef JsonSchema RefProvider(String ref);
+  class RefProvider<T>
// Changed from `typedef` to `class`.
// Changing the type of declaration is likely a breaking change.
```

```diff
@@ line 46: package:json_schema/src/json_schema/typedefs.dart @@
-  typedef Future<JsonSchema> RefProviderAsync(String ref);
// Removing a typedef is a major change.
```

```diff
@@ line 66: package:json_schema/src/json_schema/json_schema.dart @@
class JsonSchema {}
-     bool validate(dynamic instance, {bool reportMultipleErrors = false, bool parseJson = false});
+     bool validate(dynamic instance, {bool reportMultipleErrors = false, bool parseJson = false, bool validateFormats})
//    `validateFormats` was added.
//    Adding an optional parameter is a minor change.

-     JsonSchema createSchema(dynamic schema, {SchemaVersion schemaVersion, Uri fetchedFromUri, RefProvider refProvider});
+     static JsonSchema createSchema(dynamic schema, {SchemaVersion schemaVersion, Uri fetchedFromUri, RefProvider<dynamic> refProvider})
//    `type` of `refProvider` has changed.
//    Changing a parameter signature is a major change.

-     JsonSchema resolvePath(String path);
+     JsonSchema resolvePath(Uri path)
//    `type` of `path` has changed.
//    Changing a parameter signature is a major change.

-     String endPath(String path);
//    Removing a method is a major change.

-     Future<JsonSchema> createSchemaAsync(dynamic schema, {SchemaVersion schemaVersion, Uri fetchedFromUri, RefProviderAsync refProvider});
+     static Future<JsonSchema> createSchemaAsync(dynamic schema, {SchemaVersion schemaVersion, Uri fetchedFromUri, RefProvider<dynamic> refProvider})
//    `type` of `refProvider` has changed.
//    Changing a parameter signature is a major change.

-     List<ValidationError> validateWithErrors(dynamic instance, {bool parseJson = false});
+     List<ValidationError> validateWithErrors(dynamic instance, {bool parseJson = false, bool validateFormats})
//    `validateFormats` was added.
//    Adding an optional parameter is a minor change.

+     int get hashCode
//    Adding a field is a minor change.

+     bool get readOnly
//    Adding a field is a minor change.

+     JsonSchema get ifSchema
//    Adding a field is a minor change.

+     String get contentEncoding
//    Adding a field is a minor change.

+     JsonSchema get thenSchema
//    Adding a field is a minor change.

+     JsonSchema get elseSchema
//    Adding a field is a minor change.

+     bool get writeOnly
//    Adding a field is a minor change.

+     String get comment
//    Adding a field is a minor change.

+     String get contentMediaType
//    Adding a field is a minor change.

```

```diff
@@ line 77: package:json_schema/src/json_schema/validator.dart @@
class Validator {}
-     bool validate(dynamic instance, {bool reportMultipleErrors = false, bool parseJson = false});
+     bool validate(dynamic instance, {bool reportMultipleErrors = false, bool parseJson = false, bool validateFormats})
//    `validateFormats` was added.
//    Adding an optional parameter is a minor change.

```

```diff
@@ line 45: package:json_schema/src/json_schema/typedefs.dart @@
typedef JsonSchema RefProvider(String ref);

      From package:json_schema/src/json_schema/ref_provider.dart
+     T get provide
//    Adding a field is a minor change.
+     RefProvider<T> RefProvider(T provide, RefProviderType type, bool isSync)
//    Adding a constructor is a minor change.
+     bool get isSync
//    Adding a field is a minor change.
+     static RefProvider<dynamic> asyncJson(Future<Map<String, dynamic>> Function(String) provider)
//    Adding a method is a minor change.
+     RefProviderType get type
//    Adding a field is a minor change.
+     static RefProvider<dynamic> asyncSchema(Future<JsonSchema> Function(String) provider)
//    Adding a method is a minor change.
+     static RefProvider<dynamic> syncSchema(JsonSchema Function(String) provider)
//    Adding a method is a minor change.
+     static RefProvider<dynamic> syncJson(Map<String, dynamic> Function(String) provider)
//    Adding a method is a minor change.

```
<details>
<summary>Click to see 2 more API Changes</summary><p>

---
```diff
@@ line 74: package:json_schema/src/json_schema/constants.dart @@
class SchemaVersion implements Comparable<T> {}
+     static SchemaVersion get draft7
//    Adding a field is a minor change.

+     int get hashCode
//    Adding a field is a minor change.

```

```diff
@@ line 39: package:json_schema/src/json_schema/schema_type.dart @@
class SchemaType implements Comparable<T> {}
+     int get hashCode
//    Adding a field is a minor change.

```
---

</p></details>

Showing results for d0cfede540553b29e435ababf6274e4cf1a82428
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.1
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/d0cfede540553b29e435ababf6274e4cf1a82428).

**Review by michaelcarter-wf — APPROVED** [review]
+1

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
semver +1

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
