### PR TITLE
feat(package): add empty constructor for convenience

### PR DESCRIPTION
**Pull request by michaelcarter-wf**
## Ultimate problem:
- Lots of people use empty schemas as a default somewhere

## How it was fixed:
- Make it easier and also fast

## Potential areas of regression:

---

### CODE REVIEW

**Review by joshriesenbach-wk — DISMISSED** [review]
+10

Pipeline passes

**Review by joshriesenbach-wk — APPROVED** [review]
+10

If pipeline passes, good to go

**Review by jordanross-wf — DISMISSED** [review]

**Review by jordanross-wf — APPROVED** [review]

**Comment by michaelcarter-wf** [comment]
+10 

still good after formatting

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
