### PR TITLE
WAP-1552 Release json_schema 2.0.1

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* [CPLAT-4192: Update json_schema to be Dart 2 compatible](https://github.com/Workiva/json_schema/pull/39)

Requested by: @michael.carter

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.0.0...Workiva:release_json_schema_2.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.0.0...2.0.1

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5466858621239296/logs/)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (2.0.0) as the diff base.</strong></em></p> No changes to the public API found for commit 0d63cfdb09ffb25871c7416afe9c23dd5529e921

Showing results for 0d63cfdb09ffb25871c7416afe9c23dd5529e921
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.0.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/0d63cfdb09ffb25871c7416afe9c23dd5529e921).

**Comment by michaelcarter-wf** [comment]
+1

**Comment by michaelcarter-wf** [comment]
+10 

- [x] CI Passes

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
