### PR TITLE
WAP-2881: Tweak error string for root level errors

### PR DESCRIPTION
**Pull request by aaronkavlie-wf**
Error strings were always prepending the instance path even when empty, leading to root level errors like this:

```
: required prop missing: id from {"foo": "bar"}
```

An empty path is correct for anything at the root level (see the [JSON Pointer](https://tools.ietf.org/html/rfc6901) spec), so this PR just removes the prepended colon if the instance path is empty.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit ef91343744fed96234301e9a98353e5f02d1618b

Showing results for ef91343744fed96234301e9a98353e5f02d1618b
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.0.1
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/ef91343744fed96234301e9a98353e5f02d1618b).

**Comment by bryanrezende-wf** [comment]
+1

**Comment by bryanrezende-wf** [comment]
+1

**Comment by michaelcarter-wf** [comment]
+10

- [x] CI passes
- [x] Test added to ensure proper error strings

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
