### PR TITLE
WAP-2550 fix(package): update CI to target stable dart again

### PR DESCRIPTION
**Pull request by michaelcarter-wf**
## Potential areas of regression:

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit adf3d9e57ab3614275ba1f010611f427fd0f88e8

Showing results for adf3d9e57ab3614275ba1f010611f427fd0f88e8
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.0.1
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/adf3d9e57ab3614275ba1f010611f427fd0f88e8).

**Comment by aaronkavlie-wf** [comment]
+1

**Comment by michaelcarter-wf** [comment]
+10

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
