### PR TITLE
WAP-2551 Release json_schema 2.1.3

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* [WAP-2520: Improve feedback on validation failures](https://github.com/Workiva/json_schema/pull/48)

Requested by: @michael.carter

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.1.2...Workiva:release_json_schema_2.1.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.1.2...2.1.3

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5466858621239296/logs/)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by michaelcarter-wf** [comment]
+1

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (2.1.2) as the diff base.</strong></em></p> Recommendation: **:warning: Minor version bump**


```diff
@@ line 66: package:json_schema/src/json_schema/json_schema.dart @@
class JsonSchema {}
+     List<ValidationError> validateWithErrors(dynamic instance, {bool parseJson = false});
//    Adding a method is a minor change.

```

```diff
@@ line 48: package:json_schema/src/json_schema/validator.dart @@
class Validator {}
+     List<ValidationError> get errorObjects;
//    Adding a field is a minor change.

```

Showing results for 26da8c5909cef27c4e40d1faf28885c328c38db9
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.0.1
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/26da8c5909cef27c4e40d1faf28885c328c38db9).

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
