### PR TITLE
EPL-10059 Release json_schema 2.0.0-RC3

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* [use dart base image](https://github.com/Workiva/json_schema/pull/32)
* [WAP-1507 Final 2.0 Cleanup and Documentation](https://github.com/Workiva/json_schema/pull/33)

Requested by: @michaelcarter-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.0.0-RC2...Workiva:release_json_schema_2.0.0-rc3
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.0.0-RC2...2.0.0-RC3

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5466858621239296/logs/)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (2.0.0-RC2) as the diff base.</strong></em></p> Recommendation: **:bangbang: Major version bump (fyi @Workiva/semver-audit-group )**


```diff
@@ line 46: package:json_schema/src/json_schema/browser/platform_functions.dart @@
-  Future<JsonSchema> createSchemaFromUrlBrowser(String schemaUrl, {String schemaVersion});
+  Future<JsonSchema> createSchemaFromUrlBrowser(String schemaUrl, {SchemaVersion schemaVersion});
// `type` of `schemaVersion` has changed.
// Changing a parameter signature is a major change.
```

```diff
@@ line 47: package:json_schema/src/json_schema/vm/platform_functions.dart @@
-  Future<JsonSchema> createSchemaFromUrlVm(String schemaUrl, {String schemaVersion});
+  Future<JsonSchema> createSchemaFromUrlVm(String schemaUrl, {SchemaVersion schemaVersion});
// `type` of `schemaVersion` has changed.
// Changing a parameter signature is a major change.
```

```diff
@@ line 47: package:json_schema/src/json_schema/validator.dart @@
class Validator {}
-     bool validate(dynamic instance, [bool reportMultipleErrors = false]);
+     bool validate(dynamic instance, {bool reportMultipleErrors = false, bool parseJson = false});
//    `reportMultipleErrors` was removed.
//    Removing a parameter is a major change.

```

```diff
@@ line 64: package:json_schema/src/json_schema/json_schema.dart @@
class JsonSchema {}
-     String get schemaVersion;
+     SchemaVersion get schemaVersion;
//    `type` of `schemaVersion` has changed from `String` to `SchemaVersion`.
//    Changing a class field is a major change.

-     bool validate(dynamic instance);
+     bool validate(dynamic instance, {bool reportMultipleErrors = false, bool parseJson = false});
//    `parseJson` was added.
//    Adding an optional parameter is a minor change.

-     Future<JsonSchema> createSchemaFromUrl(String schemaUrl, {String schemaVersion});
+     Future<JsonSchema> createSchemaFromUrl(String schemaUrl, {SchemaVersion schemaVersion});
//    `type` of `schemaVersion` has changed.
//    Changing a parameter signature is a major change.

-     JsonSchema createSchema(dynamic data, {String schemaVersion, Uri fetchedFromUri, RefProvider refProvider});
+     JsonSchema createSchema(dynamic schema, {SchemaVersion schemaVersion, Uri fetchedFromUri, RefProvider refProvider});
//    `type` of `schemaVersion` has changed.
//    Changing a parameter signature is a major change.

-     Set<dynamic> get paths;
//    Removing a field is a major change.

-     bool get additionalProperties;
//    Removing a field is a major change.

-     dynamic get additionalItems;
//    Removing a field is a major change.

-     List<SchemaType> get schemaTypeList;
//    Removing a field is a major change.

-     Future<JsonSchema> createSchemaAsync(dynamic data, {String schemaVersion, Uri fetchedFromUri, RefProviderAsync refProvider});
+     Future<JsonSchema> createSchemaAsync(dynamic schema, {SchemaVersion schemaVersion, Uri fetchedFromUri, RefProviderAsync refProvider});
//    `type` of `schemaVersion` has changed.
//    Changing a parameter signature is a major change.

+     List<SchemaType> get typeList;
//    Adding a field is a minor change.

+     bool get additionalItemsBool;
//    Adding a field is a minor change.

+     List<dynamic> get examples;
//    Adding a field is a minor change.

+     JsonSchema get additionalItemsSchema;
//    Adding a field is a minor change.

+     bool get additionalPropertiesBool;
//    Adding a field is a minor change.

+     SchemaType get type;
//    Adding a field is a minor change.

+     String toJson();
//    Adding a method is a minor change.

```

```diff
@@ line 76: package:json_schema/src/json_schema/constants.dart @@
-  class JsonSchemaVersions {}
// Removing a class is a major change.

-     static String get draft4;
//    Removing a field is a major change.

-     static String get draft6;
//    Removing a field is a major change.

-     static List<String> allVersions = const [draft4, draft6];
//    Removing a field is a major change.

-     JsonSchemaVersions();
//    Removing a constructor is a major change.

      From dart:core/object.dart
-     bool ==(other);
//    Removing a method is a major change.
-     Type get runtimeType;
//    Removing a field is a major change.
-     int get hashCode;
//    Removing a field is a major change.
-     String toString();
//    Removing a method is a major change.
-     dynamic noSuchMethod(Invocation invocation);
//    Removing a method is a major change.

```
<details>
<summary>Click to see 2 more API Changes</summary><p>

---
```diff
@@ line 39: package:json_schema/src/json_schema/schema_type.dart @@
class SchemaType implements Comparable<T> {}
-     static SchemaType get NULL;
//    Removing a field is a major change.

-     static SchemaType get BOOLEAN;
//    Removing a field is a major change.

-     static SchemaType get ARRAY;
//    Removing a field is a major change.

-     static SchemaType get STRING;
//    Removing a field is a major change.

-     static SchemaType get OBJECT;
//    Removing a field is a major change.

-     static SchemaType get INTEGER;
//    Removing a field is a major change.

-     static SchemaType get NUMBER;
//    Removing a field is a major change.

+     static SchemaType get number;
//    Adding a field is a minor change.

+     static SchemaType get object;
//    Adding a field is a minor change.

+     static SchemaType get array;
//    Adding a field is a minor change.

+     static SchemaType get string;
//    Adding a field is a minor change.

+     static SchemaType get integer;
//    Adding a field is a minor change.

+     static SchemaType get nullValue;
//    Adding a field is a minor change.

+     static SchemaType get boolean;
//    Adding a field is a minor change.

```

```diff
@@ line 74: package:json_schema/src/json_schema/constants.dart @@
+  class SchemaVersion implements Comparable<T> {}
// Adding a class is a minor change.

+     SchemaVersion fromString(String s);
//    Adding a method is a minor change.

+     static List<SchemaVersion> get values;
//    Adding a field is a minor change.

+     int compareTo(SchemaVersion other);
//    Adding a method is a minor change.

+     int get value;
//    Adding a field is a minor change.

+     static SchemaVersion get draft4;
//    Adding a field is a minor change.

+     static SchemaVersion get draft6;
//    Adding a field is a minor change.

+     SchemaVersion copy();
//    Adding a method is a minor change.

+     String toString();
//    Adding a method is a minor change.

+     int get hashCode;
//    Adding a field is a minor change.

```
---

</p></details>

Showing results for 4ac06605ba7e83462bf3834334eadbfa02905b23
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 1.4.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/4ac06605ba7e83462bf3834334eadbfa02905b23).

**Comment by jordanross-wf** [comment]
semver +1

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
