### PR TITLE
WAP-2432 Release json_schema 2.1.1

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* [WAP-2519: Support relative filesystem refs](https://github.com/Workiva/json_schema/pull/43)
* [WAP-2536: Address failing tests on Dart 2.2](https://github.com/Workiva/json_schema/pull/44)

Requested by: @michael.carter

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/2.1.0...Workiva:release_json_schema_2.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/2.1.0...2.1.1

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5466858621239296/logs/)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by michaelcarter-wf** [comment]
+1

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (2.1.0) as the diff base.</strong></em></p> No changes to the public API found for commit 1bd1327b903e3f4675e4981c021581ded82a9727

Showing results for 1bd1327b903e3f4675e4981c021581ded82a9727
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.0.1
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/1bd1327b903e3f4675e4981c021581ded82a9727).

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
