### PR TITLE
CPRO-350 Dart1 removal phase 2 and 3

### PR DESCRIPTION
**Pull request by michaelcarter-wf**
## Ultimate problem:
- We had done an incomplete job removing all Dart1 things.

## How it was fixed:
- Follow guide and remove.

## Potential areas of regression:

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit 2750ac13c271d6ada631bda68c25df6f05d2f017

Showing results for 2750ac13c271d6ada631bda68c25df6f05d2f017
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/2750ac13c271d6ada631bda68c25df6f05d2f017).

**Review by bryanrezende-wf — APPROVED** [review]
+1

**Review by jordanross-wf — APPROVED** [review]
+1

**Comment by michaelcarter-wf** [comment]
+10

- [x] CI Passes

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
