### PR TITLE
CUI-1729: Updated changelog for version 5.0.0-rc1.

### PR DESCRIPTION
**Pull request by kyleferguson-wk**
## Ultimate problem:
Changelog needs updating before we can publish our new version `5.0.0`

## How it was fixed:
Updated the CHANGELOG.md file.

## Testing suggestions:
- N/A markdown file update only.

## Potential areas of regression:
- N/A markdown file update only.

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by michaelcarter-wf — APPROVED** [review]
+1

**Review by michaelcarter-wf — APPROVED** [review]
+1

**Comment by michaelcarter-wf** [comment]
+10

- [x] doc only change

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
