### PR TITLE
export ValidationResults

### LINKED ISSUE #175: ValidationResults not exported
## Type
Improvement
## Details

Currently to return the results to a high level, such as when you have wrapped it in a method, have to add the specific import for `ValidationResultss`, like the following.

```
import 'package:json_schema/json_schema.dart';
// ignore: implementation_imports
import 'package:json_schema/src/json_schema/models/validation_results.dart';

class JsonSchemaService {
  late final JsonSchema _schema;

  JsonSchemaService(Map<String, dynamic> schema) {
    _schema = JsonSchema.create(schema);
  }

  ValidationResults isValid(dynamic data) {
    final results = _schema.validate(data);
    return results;
  }
}
```

## Possible Solution

export ValidationResults

## Your Environment

* Version: json_schema: ^5.1.3

> __FYI:__ @michaelcarter-wf

### PR DESCRIPTION
**Pull request by mx1up**
## Ultimate problem:
`ValidationResults` can not be used outside package

## How it was fixed:
export the class

fixes #175

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by michaelcarter-wf — APPROVED** [review]
+1

**Comment by joecotton-wk** [comment]
@mx1up Thanks for adding this! Would you do us a favor and revert `5.1.8` back to `5.1.7`? That will allow our CI system to bump the version automatically. Once that's done, we'll get this one merged 👍

**Comment by mx1up** [comment]
> @mx1up Thanks for adding this! Would you do us a favor and revert `5.1.8` back to `5.1.7`? That will allow our CI system to bump the version automatically. Once that's done, we'll get this one merged 👍

sure, i reverted the commit bumping the version, which also reverts the changelog as I guess it's also no longer in use..

**Review by joecotton-wk — DISMISSED** [review]
+1

**Comment by joecotton-wk** [comment]
@mx1up Now format is failing 😔 Would you mind fixing? Thank you!

Once that's done (and barring no other problems), we'll get this merged for you.

**Comment by joecotton-wk** [comment]
@mx1up Come to think of it, I have no idea why format is failing 🤔 It's the same as it was before you reverted the version bump.

Let me see if it's our CI at fault.

**Comment by mx1up** [comment]
were those checks run on the last 2 PRs? I don't see them in the PR activity log. My guess is:
* that improperly formatted file was merged through the last PR 
* your CI pipeline rebases my branch first on master before building?
that could explain it..

**Comment by mx1up** [comment]
either way, it needs to be fixed , so I updated the fork with latest master and reformatted the file

**Review by joecotton-wk — APPROVED** [review]
+1

**Comment by joecotton-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
