### PR TITLE
Apply recommended linting rules

### PR DESCRIPTION
**Pull request by JKRhb**
## Ultimate problem:

The package does not fulfill the linting guidelines on pub.dev at the moment, leading to a worse score than theoretically possible.

## How it was fixed:

Using the recommended linting rules, I applied any suggestion that was applicable to the code base. Most suggestions were useful and an improvement regarding readability.

## Testing suggestions:

Tests and static analysis should still pass.

## Potential areas of regression:

The changes might (have) lead to an external API change, which would not be desirable. 

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(8) Security relevant changes were detected</summary>
<li>Watched keyword <code>Access-Control-Allow-Origin</code> in <code>tool/cors_headers.dart</code> line(s) ['10'] added</li>
<li>Watched keyword <code>Access-Control-Allow-Headers</code> in <code>tool/cors_headers.dart</code> line(s) ['13'] added</li>
<li>Watched keyword <code>Access-Control-Allow-Methods</code> in <code>tool/cors_headers.dart</code> line(s) ['14'] added</li>
<li>Watched keyword <code>Access-Control-Max-Age</code> in <code>tool/cors_headers.dart</code> line(s) ['15'] added</li>
<li>Watched keyword <code>Access-Control-Allow-Origin</code> in <code>tool/cors_headers.dart</code> line(s) ['10'] removed</li>
<li>Watched keyword <code>Access-Control-Allow-Headers</code> in <code>tool/cors_headers.dart</code> line(s) ['13'] removed</li>
<li>Watched keyword <code>Access-Control-Allow-Methods</code> in <code>tool/cors_headers.dart</code> line(s) ['14'] removed</li>
<li>Watched keyword <code>Access-Control-Max-Age</code> in <code>tool/cors_headers.dart</code> line(s) ['15'] removed</li>
</details>

## Action Items
* Obtain a [security review](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); reviewer should pay special attention to insights listed above
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by michaelcarter-wf — APPROVED** [review]
+1

**Comment by michaelcarter-wf** [comment]
+10

- [x] CI Passes

**Comment by dancleereman-wf** [comment]
RM +1

Dependencies will be scanned on release.

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
