### PR TITLE
use dart base image

### PR DESCRIPTION
**Pull request by josephswanson-wf**
## Ultimate problem:
- sniping smithy-runner-generator

## How it was fixed:
- use dart base image

## Testing suggestions:
- ensure CI / Travis passes

## Potential areas of regression:
- 😕 

---

> __FYA:__ @michaelcarter-wf @travisreed-wf @dustinlessard-wf @bradbenjamin-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit 2d1e8acebb18d9822a3cdef4c765a659c330a6b5

Showing results for 2d1e8acebb18d9822a3cdef4c765a659c330a6b5
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 1.4.0
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/json_schema/2d1e8acebb18d9822a3cdef4c765a659c330a6b5).

**Comment by jeffhall-wk** [comment]
+1

**Comment by jeffhall-wk** [comment]
+10 CI checks passed

**Comment by josephswanson-wf** [comment]
@Workiva/release-management-pp

**Comment by jeffhall-wk** [comment]
@michaelcarter-wf is passing CI enough to +10 on merge this?

**Comment by michaelcarter-wf** [comment]
yes!

**Comment by michaelcarter-wf** [comment]
+10

**Pull request merged**
