### PR TITLE
feat(package): run all tests on all platforms, add more format tests, logger cleanup

### PR DESCRIPTION
**Pull request by michaelcarter-wf**
## Ultimate problem:
- Most tests were only run on the Dart VM because they needed access to: 
1) the filesystem
2) creation of HTTP servers for remote $ref tests
- Logger was used inconsistently, in most cases, since we now expose detailed errors, it makes more sense for the consumer to decide what logging they need.
- We were unintentionally skipping some tests in nested format directories (all optional test anyway, whew!)

## How it was fixed:
- Moved HTTP servers to a separate file that starts in parallel alongside the test run (see Makefile)
- Tests can now (and are) run on all platforms.
- Created a `gen.dart` that copies test contents to a dart source file that can be imported in any runtime
- Clean up logging (only log on making HTTP requests)
- Make skipped tests more readable
- Add additional Make commands for dealing with the fixture server
- Auto-cleanup of fixture server when running dependent make commands
- Updated readme with instructions on using the HTTP fixture server

## Potential areas of regression:

---

> __FYA:__ @michaelcarter-wf

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by michaelcarter-wf** [comment]
+10 

- [x] CI Passes
- [x] More tests running, cross-platform
- [x] Gen works
- [x] Gen checked on CI
- [x] Serve commands have docs
- [x] Serve commands are dealt with cleanly for local dev

**Review by joshriesenbach-wk — APPROVED** [review]
+10

QA is just the pipeline passing

**Comment by michaelcarter-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
