### PR TITLE
RM-251847 Release json_schema 5.1.5

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [Fix publish workflow](https://github.com/Workiva/json_schema/pull/180)

Requested by: @joecotton-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/json_schema/compare/5.1.4...Workiva:release_json_schema_5.1.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/json_schema/compare/5.1.4...5.1.5

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5466858621239296/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5466858621239296/?repo_name=Workiva%2Fjson_schema&pull_number=181)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by joecotton-wk** [comment]
@Workiva/release-management-p

**Review by joecotton-wk — APPROVED** [review]
+1

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
